typography_spectrum: 0.32186
color:
  brandColors:
    - '#c1eaff'
    - '#212435'
    - '#b6af9f'
    - '#808277'
    - '#ffdab7'
  brandStrength: 0.75
  lightness: 0.7564278696663678
  saturation: 0.5240551785100251
  rhythmicContrast: 0.7908764064777642
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9177
analytics:
  google: null
  facebook: null
  twitter: null
name: sonnykirkley
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    url: 'https://www.linkedin.com/in/sonnykirkley'
    type: external
favicon: null
title: ' yM'
purpose: []
